apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-gateway.fullname" . }}
  labels:
    {{- include "k8s-gateway.labels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{ toYaml .Values.customLabels | trim | nindent 4 }}
    {{- end }}
data:
  Corefile: |-
    .:1053 {
        {{- if .Values.debug.enabled }}
        debug
        {{- end }}
        {{- if .Values.dnsChallenge.enabled }}
        template IN ANY {{ required "Delegated domain ('domain') is mandatory " .Values.domain }} {
           match "_acme-challenge[.](.*)[.]{{ include "k8s-gateway.regex" . }}"
           answer "{{ "{{" }} .Name {{ "}}" }} 5 IN CNAME {{ "{{" }}  index .Match 1 {{ "}}" }}.{{ required "DNS01 challenge domain is mandatory " .Values.dnsChallenge.domain }}"
           fallthrough
        }
        {{- end }}
        k8s_gateway {{ required "Delegated domain ('domain') is mandatory " .Values.domain }} {
          apex {{ .Values.apex | default (include "k8s-gateway.fqdn" .) }}
          ttl {{ .Values.ttl }}
          {{- if .Values.secondary }}
          secondary {{ .Values.secondary }}
          {{- end }}
          {{- if .Values.watchedResources }}
          resources {{ join " " .Values.watchedResources }}
          {{- end }}
          {{- if .Values.fallthrough.enabled }}
          fallthrough {{- range .Values.fallthrough.zones }} {{ . }} {{- end }}
          {{- end }}
        }
        {{- range .Values.extraZonePlugins }}
        {{ .name }}{{ if .parameters }} {{ .parameters }}{{ end }}{{ if .configBlock }} { {{ .configBlock | nindent 10 }}
        }{{ end }}
        {{- end }}
        {{- range .Values.zoneFiles }}
        file /etc/coredns/{{ .filename }}{{ if .domains }} {{ .domains }}{{ end }}
        {{- end }}
    }
  {{- range .Values.zoneFiles }}
  {{ .filename }}: {{ toYaml .contents | indent 4 }}
  {{- end }}
