apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-gateway.fullname" . }}
  labels:
{{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
    {{- include "k8s-gateway.labels" . | nindent 4 }}
    {{- if .Values.customLabels }}
    {{ toYaml .Values.customLabels | trim | nindent 4 }}
    {{- end }}
  annotations:
{{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
spec:
  selector:
    {{- include "k8s-gateway.selectorLabels" . | nindent 6 }}
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: UDP
    name: dns-udp
    targetPort: dns-udp
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- if (eq .Values.service.useTcp true) }}
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: dns-tcp
    targetPort: dns-tcp
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- end }}
  {{- if not (empty .Values.service.externalTrafficPolicy)}}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.externalIPs}}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies: 
  {{- toYaml . | nindent 6 }}
  {{- end -}}
