apiVersion: v2
name: k8s-gateway
description: A Helm chart for the k8s_gateway CoreDNS plugin
type: application
version: 2.3.0
appVersion: 0.4.0
maintainers:
  - email: mmkashin@gmail.com
    name: Michael
