apiVersion: v2
name: k8s-gateway
description: A Helm chart for the k8s_gateway CoreDNS plugin
type: application
version: 1.0.7
appVersion: 0.1.8
maintainers:
  - email: mmkashin@gmail.com
    name: Michael
